[project]
name = "kgraph"
version = "0.1.0"
description = "Knowledge Graph Visualization"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gradio>=5.32.0",
    "openai>=1.83.0",
    "pydantic>=2.11.5",
]
